services:
  - type: web
    name: alg-game-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
