export const COLORS = {
  CURRENT_NODE: "#2ecc71",
  VISITED_NODE: "#3498db",
  UPDATED_NODE: "#ff69b4",
  BACKTRACKED_NODE: "#e67e22",
  UNVISITED_NODE: "#ffffff",
  UNVISITED_BORDER: "#e74c3c",
  EDGE_NORMAL: "#95a5a6",
  EDGE_MST: "#e74c3c",
  EDGE_PATH: "#f1c40f",
  EDGE_WEIGHT: "#2980b9",
  NODE_TEXT_VISITED: "#ffffff",
  NODE_TEXT_UNVISITED: "#2c3e50",
  DISTANCE_LABEL: "#e74c3c",
  FLOW_PATH: "#2563eb",
  FLOW_EDGE: "#94a3b8",
  RESIDUAL_EDGE: "#dc2626",
  SOURCE_NODE: "#bbf7d0",
  SINK_NODE: "#fecaca",
};
